common/models/News2.php
<?php

/**
 * This is the model class for table "news2".
 *
 * The followings are the available columns in table 'news2':
 * @property integer $id
 * @property string $name
 * @property string $text
 * @property string $shortText
 * @property integer $visible
 * @property integer $cityId
 */
class News2 extends EActiveRecord
{
	public function init()
	{
		parent::init();
		$this->imagesPath = Yii::getPathOfAlias('common').'/data/news2/';
		$this->imagesUrl = '/data/news2/';
		$this->imageSizes = array(array(930, false), array(104, 104));
	}
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'news2';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, text, shortText, dateStart', 'required'),
			array('visible, cityId', 'numerical', 'integerOnly'=>true),
			array('name, shortText', 'length', 'max'=>128),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, text, shortText, visible, cityId', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'pid' => 'Pid',
			'name' => 'Название',
			'text' => 'Текст',
			'shortText' => 'Краткий текст',
			'visible' => 'Видимость',
			'image' => 'Изображение',
			'dateStart' => 'Дата',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('text',$this->text,true);
		$criteria->compare('shortText',$this->shortText,true);
		$criteria->compare('visible',$this->visible);
		$criteria->compare('cityId',$this->cityId);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
					'pageSize'=>100
			),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return News2 the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

backend/controllers/News2Controller.php
<?php
class News2Controller extends RController
{
	public function actionIndex()
	{
		$model = new News2();
		$model->cityId = (int)Yii::app()->request->cookies['city_id']->value;
		$this->render('index', array('model' => $model));
	}
	
	public function actionItem($id = false) 
	{
		if ($id !== false) 
		{
			$header = 'Редактировать';
			$model = $this->loadModel('News2', $id);
		} else  
		{
			$header = 'Добавить';
			$model = new News2();
		}
		
		if(isset($_POST['News2'])) {
			$model->attributes=$_POST['News2'];
			$model->cityId = (int)Yii::app()->request->cookies['city_id']->value;
			$model->dateStart = Yii::app()->dateFormatter->format('yyyy-MM-dd', $model->dateStart);
			
			if($model->save()) {
				if (!empty($_FILES['News2']['tmp_name']['image'])) {
				
					$model->saveImage($_FILES['News2']['tmp_name']['image'], true);
				}
				
				$this->redirect('/news2/');
			}
		}
		
		$model->dateStart = Yii::app()->dateFormatter->format('dd.MM.yyyy', $model->dateStart);
		
		$this->render('item', array('header' => $header, 'model' => $model));
	}
	
	public function actionDelete($id) {
		$model = News2::model()->findByPk($id);
		$model->deleteFull();
		$this->redirect('/news2/');
	}
}

backend/views/news2/index.php
<?php 

$this->title_h3='Новости';

$this->breadcrumbs=array(
	'Новости'
);

$this->breadcrumbs_button = '<li class="pull-right no-text-shadow">
								<a class="btn blue dash-btn" href="'.$this->createUrl('news2/item').'"><i class="icon-plus"></i>Добавить запись</a>
							</li>';

$this->menuActiveItems[BController::NEWS_MENU_ITEM] = 1;

?>
<div>
	
	<?php $this->widget('zii.widgets.grid.CGridView', array(
				'id'=>'client-grid',
				'dataProvider'=>$model->search(),
				'filter'=>null,
				'enableSorting'=>false,
				'htmlOptions'=>array('class'=>'portlet-body'),
				'itemsCssClass'=>'table table-striped table-hover',
				'summaryText'=>'',
				'loadingCssClass'=>'',
				'columns'=>array(
					array(
						'header'=>Yii::t('main','ID'),
						'name'=>'id',
					),
						
					array(
							'header'=>Yii::t('main','Name'),
							'name'=>'name',
					),					
					array(
							'header'=>'Дата',
							'name'=>'dateStart',
							'value'=>function($data) {
								return Yii::app()->dateFormatter->format('dd.MM.yyyy', $data['dateStart']);
							}
					),
					array(
							'header'=>Yii::t('main','Visible'),
							'name'=>'visible',
							'type'=>'html',
							'value'=>function($data) {
								if ($data['visible'] == 0)
									return CHtml::openTag('span', array('class'=>'label label-important')).'скрытый'.CHtml::closeTag('span');
								else
									return CHtml::openTag('span', array('class'=>'label label-success')).'видимый'.CHtml::closeTag('span');
							}
					),
					array(
						'header'=>Yii::t('main','Actions'),
						'class'=>'CButtonColumn',
						'buttons'=>array(
							'view'=>array(
								'label'=>Yii::t('main','Edit'),
								'imageUrl'=>false,
								'options'=>array('class'=>'btn mini blue-stripe'),
								'url'=>function($data) {
									return '/news2/item/'.$data['id'].'/';
								},
							),
							'add'=>array(
								'label'=>Yii::t('main','Delete'),
								'imageUrl'=>false,
								'options'=>array('class'=>'btn mini red-stripe'),
								'click'=>'confirmDelete',
								'url'=>function($data) {
									return '/news2/delete/'.$data['id'].'/';
								},
							),
						),
						'template'=>'{view} {add}',
					),
				),
				'pager'=>array('cssFile'=>false),
			)); ?>
</div>

backend/views/news2/item.php
<?php 

Yii::import('ext.imperavi-redactor-widget.ImperaviRedactorWidget');

$this->title_h3=$header;

$this->breadcrumbs=array(
	'Новости' => '/news2/',
	$header
);

Yii::app()->clientScript->registerScriptFile(
	'/plugins/bootstrap-fileupload/bootstrap-fileupload.js',
	CClientScript::POS_END
);

Yii::app()->clientScript->registerCssFile(
	'/plugins/bootstrap-fileupload/bootstrap-fileupload.css',
	'',
	CClientScript::POS_END
);

Yii::app()->clientScript->registerScriptFile(
	'/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js',
	CClientScript::POS_END
);

Yii::app()->clientScript->registerCssFile(
	'/plugins/bootstrap-datepicker/css/datepicker.css',
	'',
	CClientScript::POS_END
);

$imageUrl = '/img/noimage.gif';

if (!empty($model->id) && file_exists($model->imagesPath.'admin_preview/'.$model->id.".jpg"))
	$imageUrl = $model->imagesUrl.'admin_preview/'.$model->id.".jpg";


	$this->menuActiveItems[BController::NEWS_MENU_ITEM] = 1;

?>
<div>

	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>$model->formId,
		'enableAjaxValidation'=>false,
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
			'validateOnChange'=>false,
			'errorCssClass'=>'error',
			'afterValidate'=>'js:contentAfterClientValidate',
		),
		'htmlOptions'=>array('class'=>'form-horizontal', 'enctype'=>'multipart/form-data'),

	)); ?>
	
		<div class="control-group">
			<?php echo $form->label($model,'image',array('class'=>'control-label')); ?>
			<div class="controls">
				<div data-provides="fileupload" class="fileupload fileupload-new">
					<div style="width: 200px; height: 150px;" class="fileupload-new thumbnail">
						<img alt="" src="<?php echo $imageUrl;?>">
					</div>
					<div style="max-width: 200px; max-height: 150px; line-height: 20px;" class="fileupload-preview fileupload-exists thumbnail"></div>
					<div>
						<span class="btn btn-file"><span class="fileupload-new">Выберите изображение</span>
						<span class="fileupload-exists">Изменить</span>
						<?php echo $form->fileField($model,'image',array('class'=>'default')); ?>
						</span>
						<a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Удалить</a>
					</div>
				</div>
			</div>
		</div>
	
		<div class="control-group">
			<?php echo $form->label($model,'name',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textField($model,'name',array('class'=>'m-wrap large')); ?><br>
				<span class="help-inline"><?php echo $form->error($model,'name'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'dateStart',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textField($model,'dateStart',array('class'=>'m-wrap small date-picker', 'readonly'=>true)); ?>
				<span class="help-inline"><?php echo $form->error($model,'dateStart'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'shortText',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textArea($model,'shortText',array('class'=>'m-wrap max-width')); ?>
				<span class="help-inline"><?php echo $form->error($model,'shortText'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'text',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textArea($model,'text',array('class'=>'m-wrap redactor max-width')); ?>
				<span class="help-inline"><?php echo $form->error($model,'text'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'visible',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->checkBox($model,'visible'); ?>
				<span class="help-inline"><?php echo $form->error($model,'visible'); ?></span>
			</div>
		</div>
		
		<div class="form-actions large">
			<?php echo CHtml::htmlButton('<i class="icon-ok"></i> Сохранить', array('class' => 'btn blue', 'type' => 'submit')); ?>
			<?php if (!empty($model->id)) : ?>
				<a href="/news2/delete/<?php echo $model->id?>/" onclick="return confirmDelete()"><?php echo CHtml::htmlButton('<i class="icon-remove"></i> Удалить', array('class' => 'btn red', 'type' => 'button')); ?></a>
			<?php endif;?>
			<?php echo CHtml::htmlButton('Отменить', array('class' => 'btn', 'type' => 'reset')); ?>
		</div>
		
		<?php echo $form->hiddenField($model,'id'); ?>

	<?php $this->endWidget(); ?>

</div>

<script type="text/javascript">
	$(document).ready(function() {
		if (jQuery().datepicker) {
			$('.date-picker').datepicker({
				
				rtl : App.isRTL(),
				format: "dd.mm.yyyy"
			});
		}
	})
</script>

<?php 
$this->widget('ImperaviRedactorWidget', array(
    // The textarea selector
    'selector' => '.redactor',
    // Some options, see http://imperavi.com/redactor/docs/
    'options' => array(
		'imageUpload' => $this->createUrl('file/upload'),
		'minHeight' => 300,
		'lang' => 'ru',
	),
));

?>