common/models/Promo.php
<?php

/**
 * This is the model class for table "citys".
 *
 * The followings are the available columns in table 'citys':
 * @property integer $id
 * @property string $name
 */
class Promo extends EActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'promo';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('code', 'required'),
			array('rub, proc', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'code' => 'Промо-код',
			'rub' => 'Скидка(руб.)',
			'proc' => 'Скидка(%)'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return City the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

backend/controllers/PromoController.php
<?php

class PromoController extends RController
{
	public function actionIndex()
	{
		$model = new Promo();
		$this->render('index', array('model' => $model));
	}
	
	public function actionItem($id = false) 
	{
		if ($id !== false) 
		{
			$header = 'Редактировать';
			$model = $this->loadModel('Promo', $id);
		} else  
		{
			$header = 'Добавить';
			$model = new Promo();
		}
		
		if(isset($_POST['Promo'])) {
			$model->attributes=$_POST['Promo'];

			if($model->save()) {
				$this->redirect($this->createUrl('promo/index'));
			}
		}
		
		$this->render('item', array('header' => $header, 'model' => $model));
	}
	
	public function actionDelete($id) {
		Promo::model()->deleteByPk($id);
		$this->redirect($this->createUrl('promo/index'));
	}
}

backend/views/promo/index.php
<?php 

$this->title_h3='Промо-коды';

$this->breadcrumbs=array(
	'Промо-коды'
);

$this->breadcrumbs_button = '<li class="pull-right no-text-shadow">
								<a class="btn blue dash-btn" href="'.$this->createUrl('promo/item').'"><i class="icon-plus"></i>Добавить запись</a>
							</li>';

$this->menuActiveItems[BController::PROMO_MENU_ITEM] = 1;
?>
<div>
	
	<?php $this->widget('zii.widgets.grid.CGridView', array(
				'id'=>'client-grid',
				'dataProvider'=>$model->search(),
				'filter'=>null,
				'enableSorting'=>false,
				'htmlOptions'=>array('class'=>'portlet-body'),
				'itemsCssClass'=>'table table-striped table-hover',
				'summaryText'=>'',
				'loadingCssClass'=>'',
				'columns'=>array(
					array(
						'header'=>Yii::t('main','ID'),
						'name'=>'id',
					),
					array(
							'header'=>'Промо-код',
							'name'=>'code',
					),
					array(
							'header'=>'Скидка (руб.)',
							'name'=>'rub',
					),
					array(
							'header'=>'Скидка (%)',
							'name'=>'proc',
					),
					array(
						'header'=>Yii::t('main','Actions'),
						'class'=>'CButtonColumn',
						'buttons'=>array(
							'view'=>array(
								'label'=>Yii::t('main','Edit'),
								'imageUrl'=>false,
								'options'=>array('class'=>'btn mini blue-stripe'),
								'url'=>function($data) {
									return '/promo/item/'.$data['id'].'/';
								},
							),
							'add'=>array(
								'label'=>Yii::t('main','Delete'),
								'imageUrl'=>false,
								'options'=>array('class'=>'btn mini red-stripe'),
								'click'=>'confirmDelete',
								'url'=>function($data) {
									return '/promo/delete/'.$data['id'].'/';
								},
							),
						),
						'template'=>'{view} {add}',
					),
				),
			)); ?>
</div>

backend/views/promo/item.php
<?php 
$this->title_h3=$header;

$this->breadcrumbs=array(
	'Промо-коды' => $this->createUrl('promo/index'),
	$header
);

Yii::app()->clientScript->registerScriptFile(
	'/plugins/jquery-inputmask/jquery.inputmask.js',
	CClientScript::POS_END
);

Yii::app()->clientScript->registerScriptFile(
	'/plugins/jquery-inputmask/jquery.inputmask.date.extensions.js',
	CClientScript::POS_END
);

$this->menuActiveItems[BController::PROMO_MENU_ITEM] = 1;



?>
<div>

	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>$model->formId,
		'enableAjaxValidation'=>false,
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
			'validateOnChange'=>false,
			'errorCssClass'=>'error',
			'afterValidate'=>'js:contentAfterClientValidate',
		),
		'htmlOptions'=>array('class'=>'form-horizontal', 'rel' => $this->createUrl('review/index')),

	)); ?>
	
		<div class="control-group">
			<?php echo $form->label($model,'code',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textField($model,'code',array('class'=>'m-wrap large')); ?><br>
				<span class="help-inline"><?php echo $form->error($model,'code'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'rub',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textField($model,'rub',array('class'=>'m-wrap large')); ?><br>
				<span class="help-inline"><?php echo $form->error($model,'rub'); ?></span>
			</div>
		</div>
		
		<div class="control-group">
			<?php echo $form->label($model,'proc',array('class'=>'control-label')); ?>
			<div class="controls">
				<?php echo $form->textField($model,'proc',array('class'=>'m-wrap large')); ?><br>
				<span class="help-inline"><?php echo $form->error($model,'proc'); ?></span>
			</div>
		</div>
		
		<div class="form-actions large">
			<?php echo CHtml::htmlButton('<i class="icon-ok"></i> Сохранить', array('class' => 'btn blue', 'type' => 'submit')); ?>
			<?php if (!empty($model->id)) : ?>
				<a href="/review/delete/<?php echo $model->id?>/" onclick="return confirmDelete()"><?php echo CHtml::htmlButton('<i class="icon-remove"></i> Удалить', array('class' => 'btn red', 'type' => 'button')); ?></a>
			<?php endif;?>
			<?php echo CHtml::htmlButton('Отменить', array('class' => 'btn', 'type' => 'reset')); ?>
		</div>
		
		<?php echo $form->hiddenField($model,'id'); ?>

	<?php $this->endWidget(); ?>

</div>


<script type="text/javascript">
	$(document).ready(function() {
		$("#Review_date").inputmask("datetime", {"placeholder": "__/__/____ __:__"});
	})
</script>